# copyright: 2023 EUMETSAT
# license: LICENSE.txt
name: multicloud
channels:
  - conda-forge
  - coecms
dependencies:
  - conda-forge::python=3.9
  - conda-forge::jupyterlab
  - conda-forge::xarray
  - conda-forge::rioxarray
  - conda-forge::dask=2022.12.1
  - conda-forge::distributed=2022.12.1
  - conda-forge::netcdf4
  - conda-forge::zarr=2.16.1
  - conda-forge::s3fs=2023.9.2
  - conda-forge::matplotlib
  - conda-forge::intake
  - conda-forge::intake-xarray
  - conda-forge::pydap
  - conda-forge::rasterio
  - conda-forge::ipywidgets
  - conda-forge::conda-libmamba-solver
  - conda-forge::boto3
  - conda-forge::cartopy
  - conda-forge::geopandas
  - conda-forge::botocore
  - coecms::xmhw
  - pip
